### ISSUE TITLE
Problem while setting initial step size on a derivative free algorithms (i.e COBYLA, SBPLX...)

### ISSUE THREAD

**Issue by otavares93** [astamm/nloptr#109]
The package documentation does not show how to set initial step size of these algorithms. I'm solving a problem which the calibration of initial guess (x0 and initial step size) is very important so as to the algorithm perform well. Is there a way to change or to access the value of the initial step size? Best Regards!

**Comment by eddelbuettel** [comment]
The package is a wrapper bringing the actual numerical library that is [NLopt](https://github.com/stevengj/nlopt) to R.  You probably want to look at the [NLopt docs](https://nlopt.readthedocs.io/en/latest/).

**Comment by otavares93** [comment]
Ok, thanks !

**Comment by wcerfgba** [comment]
I am also wondering about this. I see that the option is documented at NLopt [1],  but it is not documented for nloptr [2] and does not appear implemented in the C bindings in `getOptions` [3]. Does this need to be implemented? If so I can submit a patch :)

[1] https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#initial-step-size
[2] https://astamm.github.io/nloptr/reference/nloptr.print.options.html
[3] https://github.com/astamm/nloptr/blob/master/src/nloptr.c#L524
