### ISSUE TITLE
How to specify local optimization algorithm for NLOPT_GN_MLSL?

### ISSUE THREAD

**Issue by dayuhuang0** [astamm/nloptr#11]
The mlsl function only support a particular gradient-based local optimizer. Is there a way to specify other lcao optimizer for mlsl?

**Comment by jyypma** [comment]
Could you provide a bit more information? What did you try? What did you
expect to happen? What happened (e.g. Did you get an error message?)?

Also, did you try to use NLOPT_GD_MLSL instead of NLOPT_GN_MLSL?

Best wishes,
Jelmer
