### ISSUE TITLE
set_vector_storage LBFGS

### ISSUE THREAD

**Issue by BertvanderVeen** [astamm/nloptr#122]
The documentation of `lbfgs(.)` reads:

> One parameter of this algorithm is the number m of gradients to remember from previous optimization steps. NLopt sets m to a heuristic value by default. It can be changed by the NLopt function
> set_vector_storage.

However, it does not clarify if there is a possibility in the package to specify m. Is there?

**Comment by astamm** [comment]
Well, I checked the source code. The `vector_storage` option can be changed using the C API via `nlopt_set_vector_storage()`. However, it is not accessible for change from the R API via `nloptr()` or `lbfgs()` functions. I made a PR #126 for enabling the user to change it via the R API. Can you please test it out and tell me whether that fits your need?

It should work like this:
```
library(nloptr)

## Rosenbrock Banana function and gradient in separate functions
eval_f <- function(x) {
  100 * (x[2] - x[1] * x[1])^2 + (1 - x[1])^2
}

eval_grad_f <- function(x) {
 c(
   -400 * x[1] * (x[2] - x[1] * x[1]) - 2 * (1 - x[1]), 
   200 * (x[2] - x[1] * x[1])
 )
}

# initial values
x0 <- c(-1.2, 1)

opts <- list(
  algorithm = "NLOPT_LD_LBFGS", 
  xtol_rel = 1.0e-8, 
  vector_storage = 100
)

# solve Rosenbrock Banana function
sol1 <- nloptr(
  x0 = x0, 
  eval_f = eval_f, 
  eval_grad_f = eval_grad_f, 
  opts = opts
)

sol2 <- lbfgs(
  x0 = x0, 
  fn = eval_f, 
  gr = eval_grad_f, 
  nl.info = TRUE, 
  control = list(xtol_rel = 1e-8, vector_storage = 100)
)

sol3 <- lbfgs(
  x0 = x0, 
  fn = eval_f, 
  gr = eval_grad_f, 
  nl.info = TRUE, 
  control = list(xtol_rel = 1e-8, vector_storage = 10)
)

sol1$objective
sol2$value
sol3$value
```

**Comment by BertvanderVeen** [comment]
This seems to function perfectly; thanks!
