### ISSUE TITLE
Tests for directL fail

### ISSUE THREAD

**Issue by astamm** [astamm/nloptr#138]
Running tests locally for `NLOPT_GN_DIRECT_L_RAND` fail with the following errors:

```
----- FAILED[data]: test-wrapper-direct.R<139--139>
 call| expect_equal(directLTest$par, directLControl$solution, tolerance = tol)
 diff| Mean relative difference: 0.04548268
 ----- FAILED[data]: test-wrapper-direct.R<140--140>
 call| expect_equal(directLTest$value, directLControl$objective, tolerance = tol)
 diff| Expected '-3.25641760509437', got '-3.32236801141552'
```

@aadler : I see a comment of yours suggesting you ran into this problem already. Indeed trying to set the seed in advance does not seem to help.

**Comment by astamm** [comment]
It might be that `set.seed()` or `withr::with_seed()` only affects the seed R uses but not on the C side of things. But I am surprised you do not run into this issue anymore.

**Comment by aadler** [comment]
Hi. @astamm. That's bizarre, since not only did I not run into the issue, none of the Github actions test platforms we use ran into it either. I'll try both increasing the the number of iterations and setting the seed, but you'll have to test it out as it still passes by me.

**Comment by aadler** [comment]
See https://github.com/astamm/nloptr/pull/142
