### ISSUE TITLE
Make tinytest unit test files self-sufficient

### ISSUE THREAD

**Issue by eddelbuettel** [astamm/nloptr#139]
A nice side benefit of using `tinytest` is that a test file is "just a script" that can run by itself (possibly preceded by `library(tinytest)`.  Equally nice is that we can a file by itself:  `Rscript -e 'tinytest::run_test_file(filename)'` (and ditto for `run_test_dir()`.  

I tend to do that "all the time" for my packages and have a small wrapper `tt.r` in `littler` which can flip between these modes. _However_, for `nlopt` this fails because we do not set the (optional but useful!) `library(nloptr`).   Eg:

```sh
$ tt.r -f inst/tinytest/test-hs071.R        ## as is
test-hs071.R..................    0 tests    Error in nloptr(x0 = x0, eval_f = eval_f, lb = lb, ub = ub, eval_g_ineq = eval_g_ineq,  : 
  could not find function "nloptr"
$ 
```

After adding it:
  
```sh
$ tt.r -f inst/tinytest/test-hs071.R        ## after adding 'library(nloptr)``
test-hs071.R..................    5 tests OK 0.1s
All ok, 5 results (0.1s)
$ 
```

If there is consensus that this useful I can send a quick PR that adds the line to each file, I am already a couple files in.

**Comment by aadler** [comment]
No issues from me. Anything that makes this more robust is **good**.

**Comment by astamm** [comment]
Consensus it is. Thanks for bringing that up!

**Comment by eddelbuettel** [comment]
Now on its way!

**Comment by astamm** [comment]
Thanks @eddelbuettel !
