### ISSUE TITLE
Three test files assume `options(digits=7)` but do not set it

### ISSUE THREAD

**Issue by eddelbuettel** [astamm/nloptr#140]
My machine happens to have `options(digits=6)`.  Three test files fails unless I add `options(digits=7)`:

    inst/tinytest/test-check.derivatives.R
    inst/tinytest/test-nloptr.R
    inst/tinytest/test-print.nloptr.R

Comparing against a fixed string may also be dicey in other (non-English) locales.

**Comment by aadler** [comment]
> Comparing against a fixed string may also be dicey in other (non-English) locales.

Agreed. For the pure numbers ones I think we're OK. Otherwise, we can go back and try to extract the portions of the strings which should be invariant under locales.

**Comment by aadler** [comment]
@astamm @eddelbuettel Just for completeness, we should add the change to the NEWS.

**Comment by aadler** [comment]
Unless you think it covered by the mention of "conversion to `tinytest`". That would work too.
