### ISSUE TITLE
Add functions for setting parameter bounds

### ISSUE THREAD

**Issue by mkbwang** [astamm/nloptr#145]
Hello, I want to use the `nlopt_set_lower_bound` and `nlopt_set_lower_bounds1` function for setting parameter bounds according to the [NLOPT references](https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#bound-constraints). Unfortunately the [src/nlopt.c](https://github.com/astamm/nloptr/blob/master/src/nloptr.c) seem to be outdated and only contains [`nlopt_set_lower_bounds`](https://github.com/astamm/nloptr/blob/a99a439b19079312673fba8ea908f620cdc0c422/src/nloptr.c#L782C17-L782C33). Can you update the C library? FYI, I am developing an R package, and my Rcpp codes rely on the C library imported from your package (see this [example](https://github.com/eddelbuettel/rcppnloptexample))

**Comment by jyypma** [comment]
I'm not sure what you're trying to accomplish and what doesn't work, but given that you're mentioning the Rcpp example, I'm guessing that you want to call NLopt functions from cpp code. The function `nlopt_set_lower_bounds1` is exported from [inst/include/nloptrAPI.h](https://github.com/astamm/nloptr/blob/master/inst/include/nloptrAPI.h), so you should be able to call the function from your cpp code.

**Comment by mkbwang** [comment]
Thanks for letting me know! I wasn't able to use the `nlopt_set_lower_bound` API which sets the bound of one parameter given an index. Never mind, I can get around this with the other two functions that you provide.
