### ISSUE TITLE
Update cmake installation instructions on Mac with brew

### ISSUE THREAD

**Issue by rossellhayes** [astamm/nloptr#146]
Running `sudo brew install cmake`, as suggested in [`cmake_config.sh`](https://github.com/astamm/nloptr/blob/a99a439b19079312673fba8ea908f620cdc0c422/src/scripts/cmake_config.sh#L27), now results in an error:
```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

On the other hand, `brew install --cask cmake` works and allows installation of `nloptr`.

**Comment by astamm** [comment]
Thanks @rossellhayes. I will update the script accordingly.
