### ISSUE TITLE
push a new version to CRAN?

### ISSUE THREAD

**Issue by bbolker** [astamm/nloptr#153]
The version on CRAN is two years old, and there are useful things in the development version. (I'm particularly interested in the switch to `tinytest` and corresponding decrease in upstream dependencies ...)

I haven't tried running `R CMD check`, but if you do encounter any submission-related issues, I would be happy to help troubleshoot.

**Comment by aadler** [comment]
Hi, @bbolker. For my contributions (mainly unit tests but some error fixes and efficiency tweaks), the package passed -as-CRAN. I'm pretty sure it did for @eddelbuettel as well, but it's up to @astamm to decide :).

**Comment by astamm** [comment]
Hi guys. Thanks for the reminder. I am on it.

**Comment by aadler** [comment]
Cough, cough, nudge, poke, wink, smile, cough…

**Comment by bbolker** [comment]
Still hoping for this (although I certainly have my own problems to deal with as well)

**Comment by aadler** [comment]
@astamm, what could we do to help you prepare for a new release? Is there anything outstanding in your mind or is it simply a matter of time?

**Comment by aadler** [comment]
Hi, @bbolker. I just sent PR #157 to @astamm, which addresses three outstanding issues. I do have the idea to finish cleaning up the examples and adding some more unit tests for accuracy (based on those examples), but I am not sure if that's worth holding up a new CRAN release, being that it has been so long. See what's under 2.1.0 in the PR for just how much has changed!

**Comment by aadler** [comment]
@astamm, pushing the new version to CRAN to remove `testthat` will help with many other issues as well, since `testthat` imports a good chunk of the `tidyverse` and that's causing problems in other places, like [lme4](https://github.com/lme4/lme4/issues/794).

**Comment by astamm** [comment]
I apologise for the limited bandwidth. I will submit a new release to CRAN next week.

**Comment by astamm** [comment]
On its way to CRAN as of today.

**Comment by aadler** [comment]
[97.53%](https://app.codecov.io/gh/astamm/nloptr?branch=master) coverage, so beautiful!

**Comment by astamm** [comment]
Thanks to you @aadler !
