### ISSUE TITLE
Modification of test-C-API.cpp

### ISSUE THREAD

**Issue by jinghuazhao** [astamm/nloptr#155]
I have seen this problem  from 2.0.0 including 2.0.3 when compiling on our CentOS 7 system; with gcc 6.5.0; it appears that  the calls at lines 107/8 to abs() should have been fabs(), i.e.,

    expect_true(fabs(res[0] - 1./ 3) < 1.0e-4);
    expect_true(fabs(res[1] - 8./27) < 1.0e-4);

Otherwise it would fail complaining changes need to be made on system libraries (screen output omitted) but an earlier one is here, https://cambridge-ceu.github.io/csd3/R/nloptr.html.

**Comment by aadler** [comment]
The entire test suite has been rebuilt. test-C-API.cpp was renamed (so as not to be called) in 230bdd3 and then deleted in ad0dc77.

**Comment by jinghuazhao** [comment]
Yes, I tried remotes::install_github("astamm/nloptr") with NLopt 2.7.1 and it installed smoothly as 2.0.4. I wondered if I used an earlier version of NLopt on our system but since it is resolved the issue can be closed now. Thank you so much!

**Comment by aadler** [comment]
@astamm, I think this one can be closed.

**Comment by astamm** [comment]
Thanks all.
