### ISSUE TITLE
How to install nloptr on a machine that does not have internet?

### ISSUE THREAD

**Issue by fgnu** [astamm/nloptr#16]
I am trying to install the latest version of `nloptr` from CRAN on a remote server that does not have network connectivity to the outside world. I have copied over the `nloptr_1.0.4.tar.gz` file (retrieved using `download.packages`) to a location on the remote server and am trying to install it using a `install.packages("nloptr_1.0.4.tar.gz", repos = NULL)`, but obviously, it is trying to retrieve the core `nlopt` package from http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz, and being unable, fails with (actually it stops without exiting):

```
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
In addition: Warning message:
In download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  :
  unable to resolve 'ab-initio.mit.edu'
Execution halted
/bin/tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
Warning message:
In untar(tarfile = "nlopt-2.4.2.tar.gz") :
  '/bin/tar -xf 'nlopt-2.4.2.tar.gz'' returned error code 2
configure: Starting to install library to /tmp/Rtmp8zLwyt/R.INSTALLd231e290492/nloptr/nlopt-2.4.2
./configure: line 3325: cd: nlopt-2.4.2: No such file or directory
```

So, I downloaded the `nlopt-2.4.2.tar.gz` file, and tried to place it in the location where I thought  [`$("${R_HOME}/bin/Rscript" ${r_args} -e "download.file(url='${NLOPT_URL}', destfile='${NLOPT_TGZ}')")`](https://github.com/jyypma/nloptr/blob/dc6c3baccfe787d828c573309f8cf732627230b7/configure.ac#L147) would try to place the file. However, neither `getwd()`, `/tmp/` or `~` appears to be the right location, or this strategy is not working for some other reason that I do not understand. 

It would be great to get either some idea on how to make this strategy of installing `nloptr` work, or any other ideas on how to install `nloptr` on a machine with no internet access.

**Comment by jyypma** [comment]
If you download and install the NLopt library separately, this should be
detected during the installation of nloptr and nloptr links to the
installed version of NLopt.

**Comment by fgnu** [comment]
@jyypma I no longer have a machine without internet (yay?) so I am unable to simulate this. I think you can close this, and reopen in the unlikely scenario that someone else need to do this and the above suggestion does not work.

**Comment by jangorecki** [comment]
I hit the same issue, it is a little pain for automated setup. Downloaded file seems to be only 2MB so maybe it could be shipped together in package? At least the readme could provide a commands for automated installation rather than just link to zip.
