### ISSUE TITLE
Install ERROR on some CRAN machines

### ISSUE THREAD

**Issue by astamm** [astamm/nloptr#161]
Two builds failed on CRAN machines because an ISRES unit test did not pass. See [here](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/nloptr-00check.html).

**Comment by aadler** [comment]
On it.

**Comment by astamm** [comment]
I have an ongoing PR, don't worry.

**Comment by astamm** [comment]
Fixed by #162.
