### ISSUE TITLE
Nloptr interface function has print_level option but algorithm function doesn't

### ISSUE THREAD

**Issue by ProxyCausal** [astamm/nloptr#163]
I'm trying to use print_level option but it seems this is not available with the algorithm function "slsqp".

```
Error in match.arg(names(optlist), choices = names(opts), several.ok = TRUE) : 
  'arg' should be one of “stopval”, “xtol_rel”, “maxeval”, “ftol_rel”, “ftol_abs”, “check_derivatives”, “algorithm”
```

I can use the interface but I get the error below when I don't supply functions to calculate the gradient even though this is allowed by slsqp using numerical gradients.

```
Error in is.nloptr(ret) : 
A gradient for the objective function is needed by algorithm NLOPT_LD_SLSQP but was not supplied
```

Is there a workaround or can you let us use the interface without analytical gradients?

**Comment by aadler** [comment]
In general, it is best to use the `nloptr` call to get the full functionality. I’m not in front of the code now, so I may be mistaken, but I’m not sure that when the helper functions were written, that they allowed  passing any parameters to the `opts` list. Only the ones H Borchers specifically coded for. I recommend using the full nloptr syntax if you can. If there is a real need to add multi-level parameter passing (to main call and into opts list) that will require a bit of coding. 


As for gradients, see the source code. That is because Hans coded to use the nl.gradient function when no analytic gradient was passed. You can do the same in the full nlopt call, which is exactly what the helper does.

**Comment by aadler** [comment]
I would add that if you don’t have an analytic gradient, using one calculated by differences will likely both increase the convergence time and reduce the accuracy. It’s worth comparing with a gradient free method like nelder mead or subplex, unless you have (in)equality constraints, in which case you’re stuck 😀

**Comment by aadler** [comment]
Below is the complete source code for `slsqp`. Overall, note how it is simply a conveniece function to the complete `nloptr` call, use of which allows the full functionality of the `nloptr` package. Changing your workflow to use the full call is what I would recommend for the most robust use. Two items in specific: 

1. Note how if `gr` is `NULL`, the codes passes the difference-based `nl.grad` function to the `eval_grad_f` parameter in `nloptr`. That is why you were able to "get away with" not passing a gradient function. If you cannot compute the analytic gradient yourself, you can do the same thing.
2. There is no code in the wrapper to to parse the ellipse. This is something that @bbolker is looking into in #102. As such, you cannot pass anything beyond what is explicitly mentioned. The wrapper uses the helper function `nl.opts` to set the `nloptr` call, and _its_ help specifically says "_There are more options that can be set for solvers in NLOPT. These cannot be set through their wrapper functions. To see the full list of options and algorithms, type `nloptr.print.options().`_" So, I reiterate, use the full call for full functionality.

@astamm, I recommend closing this as **wontfix** as the functionality requested exists, but not in the wrapper, and I do not recommend expanding the wrappers.

```r
slsqp <- function(x0, fn, gr = NULL, lower = NULL, upper = NULL, hin = NULL,
                  hinjac = NULL, heq = NULL, heqjac = NULL, nl.info = FALSE,
                  control = list(), deprecatedBehavior = TRUE, ...) {

  opts <- nl.opts(control)
  opts["algorithm"] <- "NLOPT_LD_SLSQP"

  fun <- match.fun(fn)
  fn  <- function(x) fun(x, ...)

  if (is.null(gr)) {
    gr <- function(x) nl.grad(x, fn)
  } else {
    .gr <- match.fun(gr)
    gr <- function(x) .gr(x, ...)
  }

  if (!is.null(hin)) {
    if (deprecatedBehavior) {
      warning("The old behavior for hin >= 0 has been deprecated. Please ",
              "restate the inequality to be <=0. The ability to use the old ",
              "behavior will be removed in a future release.")
      .hin <- match.fun(hin)
      hin <- function(x) -.hin(x, ...)      # change  hin >= 0  to  hin <= 0 !
    }

    if (is.null(hinjac)) {
      hinjac <- function(x) nl.jacobian(x, hin)
    } else if (deprecatedBehavior) {
      warning("The old behavior for hinjac >= 0 has been deprecated. Please ",
              "restate the inequality to be <=0. The ability to use the old ",
              "behavior will be removed in a future release.")
      .hinjac <- match.fun(hinjac)
      hinjac <- function(x) -.hinjac(x)
    }
  }

  if (!is.null(heq)) {
    .heq <- match.fun(heq)
    heq <- function(x) .heq(x)
    if (is.null(heqjac)) {
      heqjac <- function(x) nl.jacobian(x, heq)
    } else {
      .heqjac <- match.fun(heqjac)
      heqjac <- function(x) .heqjac(x)
    }
  }

  S0 <- nloptr(x0,
               eval_f = fn,
               eval_grad_f = gr,
               lb = lower,
               ub = upper,
               eval_g_ineq = hin,
               eval_jac_g_ineq = hinjac,
               eval_g_eq = heq,
               eval_jac_g_eq = heqjac,
               opts = opts)

  if (nl.info) print(S0)

  list(par = S0$solution, value = S0$objective, iter = S0$iterations,
       convergence = S0$status, message = S0$message)
}
```

**Comment by astamm** [comment]
I will follow @aadler recommendation here. His answer should help you @ProxyCausal.
