### ISSUE TITLE
Using CMake Binaries from another location

### ISSUE THREAD

**Issue by berkeucar** [astamm/nloptr#171]
Hello, 

First of all, thanks for the well-maintained and -documented package.  I was trying to install ggstatsplot and ggpubr to my Linux-x86_64 machine, and it failed due to the CMake version being <3.15. I understand it is required and I need to upload CMake but I cannot due to other concerns. 

I tried to create a variable named CMAKE_BIN (to point it to my CMake binary installation >3.15), however, this variable is overwritten by the cmake_call.sh script when I try to download nloptr within the R console. Could you please help me?

Thanks again for your contributions.
Best,
Berke

**Comment by berkeucar** [comment]
I was able to figure it out. Sorry...

**Comment by eddelbuettel** [comment]
What's your Linux OS?  You may aide yourself by using a pre-made binary libnloptr as this alleviates the need to build nloptr from source -- and avoids the cmake requirement.
