### ISSUE TITLE
mistake in the reference manual

### ISSUE THREAD

**Issue by nfdisco** [astamm/nloptr#2]
Hi,
I think I might have found a glitch in nloptr's reference manual. On page 5, in the Augmented Lagrangian Algorigthm part, the manual states that the argument "hin" defines the inequality constraints, hin(x) >= 0, but this appears to be a mistake.
See the following post to nlopt-discuss for details.
https://www.mail-archive.com/nlopt-discuss@ab-initio.mit.edu/msg00613.html
Regards.

**Comment by jyypma** [comment]
This is correct, it should be <= 0. I will change this in the documentation
of auglag in the file nloptr/man/auglag.Rd.

Many thanks,
Jelmer
