### ISSUE TITLE
Shipping the nlopt headers with nloptr

### ISSUE THREAD

**Issue by tvatter** [astamm/nloptr#27]
Hi,

I am working on a C++ library that uses NLopt and I am also developing an R interface.

Because only the .so is currently shipped in libs, the only solution that I see is to include the following to the package's Makevars:

```
PKG_CPPFLAGS = -I../inst/include -I"$(NLOPT_HOME)/include"
PKG_LIBS     = -L"$(NLOPT_HOME)/lib" -lnlopt  
```

where NLOPT_HOME is the address of my local install, which works fine.

However, I think that it would be fare more convenient to ship the headers along with the .so, in order to be able to simply include the following to the package's DESCRIPTION:

```
LinkingTo: 
    nloptr
```

What do you think?

**Comment by astamm** [comment]
Versions `>=2.0` should all do that now. Actually even at some point the `v1` implemented that. So this should not be an issue anymore.
