### ISSUE TITLE
another mistake in the reference manual (p. 30)

### ISSUE THREAD

**Issue by nfdisco** [astamm/nloptr#3]
According to the reference manual (page 30), functions eval_g_ineq and eval_g_eq may return a list with two elements named "objective" and "jacobian". However, it is clear from the code in nloptr.R:117 and nloptr.R:149 that the elements in the list must be named "constraints" and "jacobian".

**Comment by jyypma** [comment]
Many thanks for catching this. As the doumentation is automatically
generated, I will change this in the file man/nloptr.Rd.

Best wishes,
Jelmer
