### ISSUE TITLE
[security problem] You can't download files and not check hash

### ISSUE THREAD

**Issue by yurivict** [astamm/nloptr#30]
Yo should supply ```NLOPT_HASH=``` along with ```NLOPT_VERSION=```.

**Comment by yurivict** [comment]
Fix: https://github.com/jyypma/nloptr/pull/31

**Comment by yurivict** [comment]
https://github.com/jyypma/nloptr/pull/32

**Comment by jyypma** [comment]
Thank you for flagging this issue and providing a pull request. Checking the hash after downloading NLopt sounds like a sensible way to mitigate the security issue.

In recent commits, I have included the NLopt source code as subdirectory of src. If no pre-installed NLopt version can be found on the system during the configuration of nloptr, the included NLopt code is configured and compiled. NLopt is no longer downloaded during configuration which seems to me to solve this issue.
