### ISSUE TITLE
Issue installing nloptr with nlopt in custom directory

### ISSUE THREAD

**Issue by GarryWay** [astamm/nloptr#33]
Hi Jelmer,

I'm having issues installing nloptr due to my organization installing the nlopt package in a custom location due to security problems with downloading and installing nlopt myself. However I can't seem to figure out how to let R know where nlopt is installed when I run install.packages. I found a similar request from a previous issue which you answered here:

> If you unpack the nlopt-2.4.2.tar.gz archive and configure and install the
NLopt package, then the location of the installation should be recognized
when nloptr is installed. If the location is not automatically recognized,
you can also pass these as options to the R command that you use to install
the nloptr package (--configure-vars and --configure-args can be used to
pass the NLopt include/ and lib/ paths to nloptr).

I wasn't clear on exactly how to use the last line but this looks like it relates to my issue. I tried the command below with no luck:

`>install.packages('nloptr',method='wget',lib=.libPaths()[2],dependencies=T,configure.args=c('--with-nlopt-cflags=/swd/nlopt/include','--with-nlopt-libs=/swd/nlopt/lib'))`

(Omit)
checking nlopt.h usability... no
checking nlopt.h presence... no
checking for nlopt.h... no
configure: Need to download and build NLopt
trying URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
In addition: Warning message:
In download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  :
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz': HTTP status was '407 Proxy Authentication Required'
Execution halted
/bin/gtar: This does not look like a tar archive

gzip: stdin: unexpected end of file
/bin/gtar: Child returned status 1
/bin/gtar: Error is not recoverable: exiting now
Warning message:
In untar(tarfile = "nlopt-2.4.2.tar.gz") :
  '/bin/gtar -xf 'nlopt-2.4.2.tar.gz'' returned error code 2
configure: Starting to install library to /tmp/RtmpfvriBV/R.INSTALLd23947fb5bff/nloptr/nlopt-2.4.2
./configure: line 3325: cd: nlopt-2.4.2: No such file or directory

Ultimately my R session hangs for some time until the install finally fails. I have confirmed that the nlopt files are available on the /swd/nlopt path; I've tried reading through the configure file for more information but I'm still lost. Any help you can provide would be greatly appreciated.

Best Regards,
Garrett

**Comment by jyypma** [comment]
Hi Garrett,

The following might work:
install.packages('nloptr', method = 'wget', lib = .libPaths()[2],
dependencies = TRUE, configure.args =
"--with-nlopt-cflags='-I/swd/nlopt/include'
--with-nlopt-libs='-L/swd/nlopt/lib -lnlopt'")

Hope this helps,
Jelmer

**Comment by GarryWay** [comment]
Hi Jelmer,

Thanks, that worked to find the header file; now I have a shared object error similar to issue #15 .
> Error in dyn.load(file, DLLpath = DLLpath, …) :
> unable to load shared object ‘/home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3/nloptr/libs/nloptr.so’:
> /home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3/nloptr/libs/nloptr.so: undefined symbol: nlopt_set_maxtime

Below are the results of the same debug and install steps. I don't have access to run ldconfig.

```
cltw7031dx (~)-1013> pkg-config --exists nlopt
cltw7031dx (~)-1014> pkg-config --libs nlopt
-L/swd/nlopt/lib -lnlopt -lm  
cltw7031dx (~)-1015> pkg-config --cflags nlopt
-I/swd/nlopt/include  
cltw7031dx (~)-1016> pkg-config --modversion nlopt
2.4.2
cltw7031dx (~)-1017> ldconfig -p | grep nlopt
bash: ldconfig: command not found
cltw7031dx (~)-1018> echo $LD_LIBRARY_PATH
/swd/nlopt/lib
cltw7031dx (~)-1019> echo $PKG_CONFIG_PATH
/swd/nlopt/lib/pkgconfig
cltw7031dx (~)-1020> 

> install.packages('nloptr',method='wget',configure.args=c('--with-nlopt-cflags=-I/swd/nlopt/include','--with-nlopt-libs=-L/swd/nlopt/lib'))
Installing package into ‘/home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
--2017-07-14 11:02:45--  https://mran.microsoft.com/snapshot/2016-06-01/src/contrib/nloptr_1.0.4.tar.gz
Saving to: “/tmp/RtmpZRvYHj/downloaded_packages/nloptr_1.0.4.tar.gz”

     0K .......... .......... .......... .......... .......... 14%  190K 2s
    50K .......... .......... .......... .......... .......... 28%  771K 1s
   100K .......... .......... .......... .......... .......... 43%  295K 1s
   150K .......... .......... .......... .......... .......... 57%  211K 1s
   200K .......... .......... .......... .......... .......... 72%  395K 0s
   250K .......... .......... .......... .......... .......... 86% 77.8K 0s
   300K .......... .......... .......... .......... .....     100%  145K=1.8s

2017-07-14 11:02:49 (190 KB/s) - “/tmp/RtmpZRvYHj/downloaded_packages/nloptr_1.0.4.tar.gz” saved [353942/353942]

* installing *source* package ‘nloptr’ ...
** package ‘nloptr’ successfully unpacked and MD5 sums checked
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for pkg-config... yes
configure: Now testing for NLopt header file.
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking nlopt.h usability... yes
checking nlopt.h presence... yes
checking for nlopt.h... yes
configure: Suitable NLopt library found.
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -I/swd/rlx/microsoft_ROpen/usr/lib64/MRO-3.3.0/R-3.3.0/lib64/R/include -DNDEBUG  -I/opt/build/build/include -DU_STATIC_IMPLEMENTATION    -fpic  -g -O2  -c dummy.cpp -o dummy.o
gcc -std=gnu99 -I/swd/rlx/microsoft_ROpen/usr/lib64/MRO-3.3.0/R-3.3.0/lib64/R/include -DNDEBUG  -I/opt/build/build/include -DU_STATIC_IMPLEMENTATION   -I/swd/nlopt/include -fpic  -I/opt/build/build/include -DU_STATIC_IMPLEMENTATION  -c nloptr.c -o nloptr.o
g++ -shared -L/swd/rlx/microsoft_ROpen/usr/lib64/MRO-3.3.0/R-3.3.0/lib64/R/lib -L/opt/build/build/lib -o nloptr.so dummy.o nloptr.o -L/swd/nlopt/lib -L/swd/rlx/microsoft_ROpen/usr/lib64/MRO-3.3.0/R-3.3.0/lib64/R/lib -lR
installing to /home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3/nloptr/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3/nloptr/libs/nloptr.so':
  /home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3/nloptr/libs/nloptr.so: undefined symbol: nlopt_set_maxtime
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/wayca00g/R/x86_64-pc-linux-gnu-library/3.3/nloptr’
Warning in install.packages :
  installation of package ‘nloptr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpZRvYHj/downloaded_packages’
```

**Comment by wiscannis** [comment]
I was able to get it to link properly with an additional argument in the link line, "-Wl,-rpath":

configure.args = "--with-nlopt-cflags='-I/swd/nlopt/include' --with-nlopt-libs='-L/swd/nlopt/lib -lnlopt -Wl,-rpath=/swd/nlopt/lib'"

**Comment by aisthesis** [comment]
One solution seems to be to install `nlopt` using your package manager outside of R. On my Mac using homebrew I installed with `brew install nlopt`. This was inspired by others reporting that they had fixed the problem on Ubuntu using `sudo apt-get install libnlopt-dev`.

**Comment by smmutangyuan** [comment]
brew install pkg-config.   can solved it

**Comment by Hyunglok-Kim** [comment]
If someone gets errors when installing Rstudio faraway package on Ubuntu 18.04.4 LTS, try installing libnlopt-dev first. It solved my problem: sudo apt-get install libnlopt-dev

**Comment by astamm** [comment]
We just released `v2.0.0`. We now rely on `Cmake` when building from source. Can you test and tell us if it fixes whatever issue you had in the past please?

**Comment by Hyunglok-Kim** [comment]
Hi Aymetric,
I forgot which questions I made in the past.
Could you please forward my previous questions?
Thanks,
Hyung

**Comment by astamm** [comment]
Thanks for getting back at me. The issue was actually filed by @GarryWay. You had the final word there saying that installing `libnlopt-dev` solved the issue for you. I wonder if someone still has problems in this feed with the new `v2.0.0` version.

**Comment by Hyunglok-Kim** [comment]
Could you please forward the relevant link to me?

**Comment by eddelbuettel** [comment]
It is all at https://github.com/astamm/nloptr/issues/33 (even if you see it by email, the main / primary spot is the GitHub issue).
