### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by mikeaalv** [astamm/nloptr#41]
I am using global optimization for optimizing an ODE set. While doing the optimization, some of the point would be improper and causing error for ODE. This would cause the optimization to stop. Is there any method to ignore or remove the improper point and go on optimization rather than just stop? Is there any error handling parameter for the nloptr?

**Comment by astamm** [comment]
I think the best place to have an answer for this is to file an issue in the original `nlopt` repo: https://github.com/stevengj/nlopt/issues.
