### ISSUE TITLE
Nelder-Mead segfault on development version

### ISSUE THREAD

**Issue by lucasnell** [astamm/nloptr#42]
Using the GitHub version of nloptr, the following R command...
```r
nloptr::neldermead(c(0, 1), fn = function(x) sqrt(abs(x[1])))
```
causes the following error (this happens with `nloptr::sbplx`, too):
```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("NLoptR_Optimize", ret, PACKAGE = "nloptr")
 2: nloptr(x0, fn, lb = lower, ub = upper, opts = opts)
 3: nloptr::neldermead(c(0, 1), fn = function(x) sqrt(abs(x[1])))
```

The same error occurs when I try to use nlopt directly in C++ via `Rcpp`:
```cpp
#include <Rcpp.h>
#include <cmath>
#include <nloptrAPI.h>

using namespace Rcpp;

double f(unsigned n, const double* x, double* grad, void* f_data) {
    return std::sqrt(std::abs(x[0]));
}
//[[Rcpp::export]]
void test_nlopt() {
    unsigned n = 2;
    double x [2] = {0,1};
    double min_f;

    nlopt_opt opt = nlopt_create(NLOPT_LN_NELDERMEAD, n);
    nlopt_set_min_objective(opt, f, NULL);
    nlopt_set_ftol_rel(opt, 0.00000002);
    nlopt_set_maxeval(opt, 1000);

    nlopt_result res = nlopt_optimize(opt, x, &min_f);

    return;
}
```
This error occurs even when I link directly to nlop using `nloptr.h` instead of `nloptrAPI.h`.

Using just nlopt by itself in a self-contained C++ program works without error.

I'm compiling using clang version 4.0.0.

**Comment by eddelbuettel** [comment]
Seems to work here:

```sh
edd@rob:~/git/nloptr(master)$ Rscript -e 'nloptr::neldermead(c(0, 1), fn = function(x) sqrt(abs(x[1])))'
$par
[1] 0 2

$value
[1] 0

$iter
[1] 1000

$convergence
[1] 5

$message
[1] "NLOPT_MAXEVAL_REACHED: Optimization stopped because maxeval (above) was reached."

edd@rob:~/git/nloptr(master)$ 
```

**Comment by lucasnell** [comment]
Okay, so presumably it's a compilation issue on my end. I'll play around with that and report back. Thanks for the quick response.

**Comment by lucasnell** [comment]
It works on my Lubuntu VM, as expected based on your response.

The problem occurs only on my mac when I have nlopt installed as an external library (using homebrew). When I let nloptr install nlopt for me, it works perfectly using both clang4 and the default compiler. This works for me.
