### ISSUE TITLE
Install error - cannot run C++ compiled programs

### ISSUE THREAD

**Issue by firmbeliever** [astamm/nloptr#45]
I'm running MAC OS 10.13.4, have r-studio installed via conda.  In r-studio, I'm trying to install a package (faraway) for which nloptr is a dependency.  When it tries to install nloptr, I'm getting this error:

checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/var/folders/76/szjpgm796kb66l8d_lf87xnm0000gn/T/RtmpVqi9F1/R.INSTALL4b371b1b3c4/nloptr':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
ERROR: configuration failed for package ‘nloptr’

I've updated conda and my r environment, but this still persists.

**Comment by jyypma** [comment]
I'm not familiar with conda, so I'm afraid I won't be able to help here.

**Comment by eddelbuettel** [comment]
Conda generally does not seem to mix well with R.  And everything we do generally works outside of Conda, so I generally recommend to not mix and match...

**Comment by eprparadox** [comment]
did anyone find a resolution to this within conda?

**Comment by firmbeliever** [comment]
I never did.  I encountered a few very annoying problems like this so eventually stopped using r-studio via conda (just did a "regular" install of r and r-studio).  So far, so good.

**Comment by c0d3sh3lf** [comment]
You can try running below command in your terminal
`conda install -c jmorrison r-faraway 
`
This should install the nloptr dependency automatically. If it doesn't then run the below command first and then execute the above command.
`conda install -c r r-nloptr`
