### ISSUE TITLE
slow down from version 1.00 to 1.2.1

### ISSUE THREAD

**Issue by haohua** [astamm/nloptr#53]
Hi Guys, 

I don't know if you notice or not, but after i upgrade nloptr from 1.0.0 to 1.2.1, the nloptr takes three times longer for my use case. 

1. with nloptr_1.2.1  time (secs): user 716.99, system 1749.41, **elapsed 191.01**
2. with nltopr_1.0.0  time (secs): user 513.21, system 1561.3, **elapsed 67.08**
A good thing is that the final output is exactly the same from two versions of package.  

I haven't created any test code for you guys to test, but if necessary, i'll create one. 

I don't know if this is because of the changes in underlying nlopt C code , or some wrapper function in nloptr. 

any thoughts?

**Comment by jyypma** [comment]
Can you give some more information about the tests. E.g. how many
iterations were needed to reach the optimum? Which algorithm did you use?
