### ISSUE TITLE
nloptr can't find nloptrAPI.h 

### ISSUE THREAD

**Issue by bruc** [astamm/nloptr#54]
When I attempt to run the nloptr unit tests, I get a compilation error because the compiler can't find nloptrAPI.h. nloptrAPI.h was installed in the R system environment on the relative path, lib64/R/library/nloptr/include.

When I run 'strace' to check what files are being opened, the GNU c++ compiler is not looking in the installed location for nloptrAPI.h.

Here's the strace line for the call to g++ that's problematic. 

[pid 29615] execve("/bin/sh", ["/bin/sh", "-c", "g++  -I\"/opt/work/binaries/R-3.5.2/lib64/R/include\" -DNDEBUG   -I/opt/work/include   -I/opt/work/include   -fpic  -g -O2  -c file739f3fa23777.cpp -o file739f3fa23777.o"], 0x1985690 /* 94 vars */ <unfinished ...>

Shouldn't nloptr be including -I/opt/work/binaries/R-3.5.2/lib64/R/library/nloptr/include in the g++ call? Alternatively, shouldn't the install script copy nloptrAPI.h into lib64/R/include?

**Comment by eddelbuettel** [comment]
Could your setup be non-standard in some way?  CRAN itself runs, and re-runs these tests, and does not seem to have an issue, see https://cloud.r-project.org/web/checks/check_results_nloptr.html

**Comment by bruc** [comment]
Yes, it is highly configured. I'm running on Redhat 6, which is old, and I need to build later versions of many system components in order to get the entire environment to work together.

The key question that I have is "how does a package control what compiler options are used when it has to compile generated C++ code?" I suspect that my configuration isn't properly specifying that nloptr should look in the location where nloptrAPI.h is located.

**Comment by bruc** [comment]
I have a related question: how I can I construct an environment that matches exactly the test environment that CRAN uses (as you referenced above)? I haven't been able to find the specification of what's in the CRAN test environment.

**Comment by eddelbuettel** [comment]
In general, "we" (as package authors) can just rely on R to do the right thing for us via a "contract" (details of which are in the _Writing R Extensions_ manual.

In brief:
- a package will always have a `-I....` switch for R headers
- if a package needs its own headers from `inst/include` one usually adds `-I../inst/include` in `src/Makevars`
- when a package needs headers from another package it declares `LinkingTo: otherPkg` and a `-I...` flag to `otherPkg` will be added.

Now, unit tests are trickier.  They run at test time again an temporary installation.  But they always run.  And I don;t understand how nloptr would finds its own headers _everywhere_ these tests run, but not on your system.

Also, the `execve()` trace you show is kinda meaningless.  What matters for is the explicit system call of `R CMD INSTALL ....` etc we see during installation.   Again, what happens in tests is different and a little hidden.

Good luck.   

Oh, and mind you:  it could also be compiler age.

**Comment by eddelbuettel** [comment]
There is nothing to it.  CRAN has several platforms, one of them is _e.g._ Debian testing -- so just fire up a Docker container with Debian testing.  I even built a few for you starting with

- Rocker's r-base https://hub.docker.com/r/rocker/r-base/, or
- A custom Rcpp container on top of it:  https://cloud.docker.com/u/rcpp/repository/docker/rcpp/run
- Plus a few other package https://cloud.docker.com/u/rcpp/repository/docker/rcpp/plus

**Comment by bruc** [comment]
I am definitely hamstrung running RHEL 6 -- it does not support Docker.
Compiler age is not a problem -- Redhat provides package collections that allow a user to get recent compilers. I'm using gcc 8.2.1 for the above.

BTW, the execve() is not meaningless, it's informing me that the compiler call in nloptr is missing the -I option that would find the header file it's looking for. 

I'm running the tests using this command:

	if R CMD check \
	     --no-stop-on-test-error \
	     --no-examples \
	     --ignore-vignettes \
	     --no-manual \
	     --install=skip \
	     $pkg_tarball > check.$pkg.log 2>&1

I will read the Writing R Extensions manual more carefully to see if I can answer my questions.

Thank you for all your suggestions.

**Comment by eddelbuettel** [comment]
> I am definitely hamstrung running RHEL 6 -- it does not support Docker.

I know. I meant that more in the sense of _quickly firing up an alternate environment for checking_ on another machine, your laptop, on AWS, ...

**Comment by astamm** [comment]
We just released v2.0.0. Hopefully that solves your issue (if it is still an issue after all this time). Can you try it please?
