### ISSUE TITLE
Compilation fails on openSUSE

### ISSUE THREAD

**Issue by thomaszumbrunn** [astamm/nloptr#6]
I don't know whether anybody brought this to your attention:
https://stat.ethz.ch/pipermail/r-help/2013-June/355446.html

The described workaround also worked with R 3.1.1 on openSUSE 13.1.

**Comment by jyypma** [comment]
Thank you for your message. I will make a note of this in the vignette.

Recently, Dirk Eddelbuettel created a configure script for nloptr to solve
some installation issues on Debian. I guess the configure.ac script can be
adapted to solve this issue. Any patches are of course more than welcome.
