### ISSUE TITLE
Installation issue: Configuration failed on R 3.6.3 on Mac OS

### ISSUE THREAD

**Issue by hessakh** [astamm/nloptr#60]
I got this error when I tried to install nloptr from CRAN using `install.packages("nloptr")`:

make[3]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/private/var/folders/3q/w0svc8157797sgh87crz026m0000gn/T/RtmpyJVPSM/R.INSTALL14267c1e3cba/nloptr/src/nlopt_src/include'
/bin/sh: .././install-sh: Permission denied
make[3]: *** [install-includeHEADERS] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
ERROR: configuration failed for package ‘nloptr’

I got around this by using `devtools::install_github("jyypma\nloptr")` works but I was wondering if there's a different way to get the CRAN installation to work on Mac's.

**Comment by eddelbuettel** [comment]
> tried to install nloptr from CRAN .... Using devtools [github URL]

That is not correct. 
- to install from CRAN, use `install.packages("nloptr")`. 
- to install from GitHub [1] use the correct repo URL with a forward slash

[1] I personally recommend against GitHub installations as _ex ante_ you never know which, if any, commit you will get. I _always_ prefer and use CRAN relases unless I have a _strong reason_ not to.  I don't think you have one here.

**Comment by eddelbuettel** [comment]
Looking at CRAN's results at https://cloud.r-project.org/web/checks/check_results_nloptr.html though, I see that its two macOS builds also error.  Someone with access to a macOS machine (I don't have one) will need to look into that,

**Comment by jyypma** [comment]
This has been fixed in version 1.2.2.1, which is on CRAN. Many thanks to
the CRAN maintainers for performing the fix.

**Comment by eddelbuettel** [comment]
And as I noticed when updating the Debian package for `nloptr`, the change appears to just be a mode change to 0755 for the installer script.
