### ISSUE TITLE
nlopt_create not provided by nloptr

### ISSUE THREAD

**Issue by astamm** [astamm/nloptr#62]
When using nloptr in another package via the C interface provided by the `nloptrAPI.h` file, it recently fails with the following error: `nlopt_create` not provided by nloptr. I see the same error is now happening here: <https://github.com/jchiquet/RcppArmadilloNLoptExample>. I am not sure what's going on here. Actually, it throws this error with any nloptr C registered function. Could it be something caused by the latest R release? Could you please provide a fix?

**Comment by jyypma** [comment]
Could you supply a bit more details (OS, R version, compiler version, minimal reproducible example, error message, etc.)? The unit test https://github.com/jyypma/nloptr/blob/master/tests/testthat/test-C-api.R contains examples to test the C interface. Do the unit tests fail for you?

**Comment by eddelbuettel** [comment]
And for what it is worth, my [RcppNLoptExample](http://cloud.r-project.org/package=RcppNLoptExample) package also continues to test cleanly.

**Comment by astamm** [comment]
I thoroughly compared @eddelbuettel package against Julien Chiquet’s and mine. It appears that @eddelbuettel uses both `useDynLib(“package”, .registration=TRUE)` and `import(nloptr)` in the `NAMESPACE` file. Julien uses the second but not the first and I was using only the first one without explicit import, because I thought that the namespace `nloptr::` was defined, which is not the case. Bottom line, setting up my package in the exact same way as @eddelbuettel did works fine.

**Comment by jyypma** [comment]
Glad you found a solution and thanks for sharing!
