### ISSUE TITLE
nloptr duplicate symbols when using the C API

### ISSUE THREAD

**Issue by astamm** [astamm/nloptr#63]
If the `include <nloptrAPI.h>` is made in a header file (with appropriate internal safe guards `#ifndef` and that this header is in turn included in various `.cpp` files, then the compiler (at least on macOS 10.15.4) complains that all nlopt symbols declared in the `nloptrAPI.h` file are duplicated. I made a minimal reproducible example by forking @eddelbuettel package here: <https://github.com/astamm/rcppnloptexample>. The versioned code compiles smoothly but if you uncomment the include in <https://github.com/astamm/rcppnloptexample/blob/master/src/other_cpp.cpp>, then the compiler complains.

**Comment by astamm** [comment]
It turns out that in the file `nloptrAPI.h`, you define functions directly in the header. So prefixing them with `inline` solves this issue. If you agree, I can make a PR for this simple modification unless you prefer to do it yourself. Let me know.

**Comment by jyypma** [comment]
Many thanks for the PR! I'll have a closer look in a few days.
