### ISSUE TITLE
Installation of nloptr package failed on AIX7.2

### ISSUE THREAD

**Issue by bergen288** [astamm/nloptr#67]
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server with no internet access. My installation with nloptr package failed and I am clueless.  The whole log is attached at the bottom.  Below are last few lines.  Can you please help me to figure out what's wrong?
Thanks.
```r
mv -f .deps/qsort_r.Tpo .deps/qsort_r.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile g++ -maix64 -std=gnu++11 -DHAVE_CONFIG_H -I. -I..  -I../api   -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM -MT rescale.lo -MD -MP -MF .deps/rescale.Tpo -c -o rescale.lo rescale.c
libtool: compile:  g++ -maix64 -std=gnu++11 -DHAVE_CONFIG_H -I. -I.. -I../api -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM -MT rescale.lo -MD -MP -MF .deps/rescale.Tpo -c rescale.c  -DPIC -o .libs/rescale.o
mv -f .deps/rescale.Tpo .deps/rescale.Plo
/bin/sh ../libtool  --tag=CC   --mode=link g++ -maix64 -std=gnu++11  -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM   -o libutil.la  mt19937ar.lo sobolseq.lo timer.lo stop.lo redblack.lo qsort_r.lo rescale.lo  -lm 
libtool: link: ar cru .libs/libutil.a .libs/mt19937ar.o .libs/sobolseq.o .libs/timer.o .libs/stop.o .libs/redblack.o .libs/qsort_r.o .libs/rescale.o 
ar: 0707-126 .libs/mt19937ar.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 .libs/sobolseq.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 .libs/timer.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 .libs/stop.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 .libs/redblack.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 .libs/qsort_r.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
ar: 0707-126 .libs/rescale.o is not valid with the current object file mode.
	Use the -X option to specify the desired object mode.
make[3]: *** [Makefile:371: libutil.la] Error 7
make[3]: Leaving directory '/tmp/RtmpT3pqia/R.INSTALL3d023035021285/nloptr/src/nlopt_src/util'
make[2]: *** [Makefile:574: all-recursive] Error 1
make[2]: Leaving directory '/tmp/RtmpT3pqia/R.INSTALL3d023035021285/nloptr/src/nlopt_src'
make[1]: *** [Makefile:438: all] Error 2
make[1]: Leaving directory '/tmp/RtmpT3pqia/R.INSTALL3d023035021285/nloptr/src/nlopt_src'
ERROR: configuration failed for package 'nloptr'
* removing '/software/R/site-library/nloptr'
make: *** [makefile:5: all] Error 1
```
[nloptr.log](https://github.com/jyypma/nloptr/files/4759059/nloptr.log)

**Comment by eddelbuettel** [comment]
I recommend the same as you were told in https://github.com/rstudio/httpuv/issues/278 : try downloading the `nlopt` library from its site and installing it into a "visible" place like `/usr/local/lib` and `/usr/local/include`.  The `nloptr` package will then use the existing version of `nlopt` and "only" do an R package build around it which may be simpler.

**Comment by bergen288** [comment]
The compilation of nlopt failed.  See https://github.com/stevengj/nlopt/issues/335.
Thanks.

**Comment by bergen288** [comment]
I went to ```nloptr/src/nlopt_src``` and run ```./configure```.  It finished successfully.  The next make step failed with the following information:
```r
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../api -g -O2 -MT qsort_r.lo -MD -MP -MF .deps/qsort_r.Tpo -c qsort_r.c -o qsort_r.o
qsort_r.c:1:8: error: expected identifier or '(' before string constant
 extern "C" {
        ^~~
make[2]: *** [Makefile:416: qsort_r.lo] Error 1
make[2]: Leaving directory '/software/R/source3/nloptr/src/nlopt_src/util'
make[1]: *** [Makefile:574: all-recursive] Error 1
make[1]: Leaving directory '/software/R/source3/nloptr/src/nlopt_src'
make: *** [Makefile:438: all] Error 2
```
So it doesn't like the 1st line in qsort_r.c which is ```extern "C" {```.  I don't see ```extern "C" {``` as the 1st line in other c files.  What's wrong with it?

**Comment by bergen288** [comment]
```extern "C"``` is the C++ keyword  while  ```qsort_r.c``` is the C program.  That's why qsort_r.c doesn't like it.  So I delete ```extern "C" {}``` part before make step.  Now it gives me new error message.  What is __get_tpointer here?
```r
mv -f .deps/testopt.Tpo .deps/testopt.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2   -o testopt testfuncs.o testopt.o ../libnlopt.la -lm 
libtool: link: g++ -g -O2 -o testopt testfuncs.o testopt.o  ../.libs/libnlopt.a -lm
ld: 0711-317 ERROR: Undefined symbol: __get_tpointer
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
make[2]: *** [Makefile:381: testopt] Error 1
make[2]: Leaving directory '/software/R/source3/nloptr/src/nlopt_src/test'
make[1]: *** [Makefile:574: all-recursive] Error 1
make[1]: Leaving directory '/software/R/source3/nloptr/src/nlopt_src'
make: *** [Makefile:438: all] Error 2
```

**Comment by eddelbuettel** [comment]
I think you are at the wrong repo.  You are fighting nlopt, not integration with nloptr. 

Also, `extern "C"` is a C++ construct to have it use C function signatures (which are portable).  See C++ texts for more.  Files containing it are usually compiled by a C++ compiler.  

More at https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c

**Comment by bergen288** [comment]
My ```nlopt``` is installed successfully with the following output:
```r
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/pkgconfig/nlopt.pc
-- Installing: /usr/local/include/nlopt.h
-- Installing: /usr/local/include/nlopt.hpp
-- Installing: /usr/local/include/nlopt.f
-- Installing: /usr/local/lib/libnlopt.a
-- Up-to-date: /usr/local/lib/libnlopt.a
-- Installing: /usr/local/lib/cmake/nlopt/NLoptLibraryDepends.cmake
-- Installing: /usr/local/lib/cmake/nlopt/NLoptLibraryDepends-release.cmake
-- Installing: /usr/local/lib/cmake/nlopt/NLoptConfig.cmake
-- Installing: /usr/local/lib/cmake/nlopt/NLoptConfigVersion.cmake
-- Installing: /usr/local/share/man/man3/nlopt.3
-- Installing: /usr/local/share/man/man3/nlopt_minimize.3
-- Installing: /usr/local/share/man/man3/nlopt_minimize_constrained.3
```
I try to re-install nloptr package.  Its compilation is finished successfully, but failed at very last step:
```r
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'nloptr' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/software/R/site-library/00LOCK-nloptr/00new/nloptr/libs/nloptr.so':
  rtld: 0712-001 Symbol nlopt_srand was referenced
      from module /software/R/site-library/00LOCK-nloptr/00new/nloptr/libs/nloptr.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol nlopt_version was referenced
      from module /software/R/site-library/00LOCK-nloptr/00new/nloptr/libs/nloptr.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol nlopt_create was referenced
      from module /software/R/site-library/00LOCK-nloptr/00new/nloptr/libs/nloptr.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol nlopt_destroy was referenced
      from module /software/R/site-library/00LOCK-nloptr/00new/nloptr/libs/nloptr.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol nlopt_optimize was referenced
      from module /software/R/site-library/00LOCK-nlo
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/software/R/site-library/nloptr'
```
What's wrong with nloptr.so?  Attached is the complete log file.
[nloptr.log](https://github.com/jyypma/nloptr/files/4819985/nloptr.log)

**Comment by eddelbuettel** [comment]
Well how should we know?  You are the only one with an AIX system here.  That is likely between you and your linker.  

You are trying to embed a _statically_ linked `libnlopt.a` into a dynamically linked and loaded R packages. That sometimes requires special compiler flags for the static library to be reloadable.  Maybe that is missing?  Just a guess.

Why exactly are you trying (and from I can see via interactions on a number of repos with) to build everything in AIX?  You can get a decent Linux machine for cheap and avoid all this time wasted...

**Comment by bergen288** [comment]
Dirk:
My AIX server is a powerful SAS server on Atomic S924 system.  My boss would like to have R and Python installed as the complement of SAS on the same AIX server.  I am not the expert of gcc/g++ compilation so I have no clue the root cause of failed nloptr installation.  Your hint gives me new direction to investigate.
Thanks.

**Comment by eddelbuettel** [comment]
@bergen288 Understood.  I once worked on AIX myself, but that was a departmental server a quarter centry ago. You are now paying a real cost of working on an unused system as you are the first one to hit the speed bumps.

But that is how open source works: you have the itch, you get to fix it.  We will adjust as needed.

And just in case you have not seen it:  R Core shares some tips for unusual system in the (as I recall) [R Install + Admin manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html).

**Comment by astamm** [comment]
This issue is more the a year old. Maybe the new 2.0.0 release solves your issue though. Please try it.
