### ISSUE TITLE
Is there a way to maximize objective function?

### ISSUE THREAD

**Issue by samssann** [astamm/nloptr#69]
[NLopt ](https://nlopt.readthedocs.io/en/latest/NLopt_C-plus-plus_Reference/#objective-function) shows that there is a way to set a min or max objective funtion. Is this available in the R interface?

**Comment by eddelbuettel** [comment]
The usual trick, shown in most courses or books, is add a multiplication of your final objective function result by -1.

**Comment by samssann** [comment]
Thank you Dirk, I am aware. Just asking out of curiosity if there is an undocumented options parameter for maximization.

e.g.
`nloptr(..., opts = list(maximize = TRUE))`

**Comment by eddelbuettel** [comment]
Hm, we are not hiding the code from you.  Did you _look_ at the code?

**Comment by samssann** [comment]
I did. But my R and C can be a bit rusty, so I just wanted to double check (since other NLopt interfaces have the ability to set max objective functions). I infer that this is not possible and will be closing the issue. Have a nice day.
