### ISSUE TITLE
Test failure on ARM64 and x86_64（v1.2.2.2）

### ISSUE THREAD

**Issue by fubingting** [astamm/nloptr#71]
When Rscript testthat.R on ARM64,The test fails and the following error occurs:
Loading required package: nloptr
══ Failed tests ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
── Failure (test-hs071.R:102:5): Test HS071. ───────────────────────────────────
res$solution not equal to `solution.opt`.
3/4 mismatches (average diff: 5.54e-06)
[2] 4.74 - 4.74 ==  6.69e-06
[3] 3.82 - 3.82 == -8.73e-06
[4] 1.38 - 1.38 ==  1.21e-06

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 46 ]
Error: Test failures

**Comment by fubingting** [comment]
The test-hs071.R results are as follows:
    #1 4.743006 3.821141 1.379409
    cat("res$solution:",res$solution)
    #1 4.743 3.82115 1.379408
    cat("solution.opt:",solution.opt)

**Comment by astamm** [comment]
That should be solved in current release.
