### ISSUE TITLE
Compiled nlopt version 2.4 for windows is using the wrong compiler from RTools

### ISSUE THREAD

**Issue by stefanoborini** [astamm/nloptr#72]
I am trying to install nloptr 1.2.1, but on windows it does not compile correctly. The errors happen at linking and they contain messages such as the following

1. undefined reference to __gxx_personality_sj
2. undefined reference to _Unwind_SjLj_Register
3. undefined reference to _Unwind_SjLj_Unregister
4. undefined reference to _Unwind_SjLj_Resume

[This stackoverflow post](https://stackoverflow.com/questions/7751640/undefined-reference-to-gxx-personality-sj0) seems to indicate that the NLopt package has been compiled on gcc, but RTools 3.6.3 provides the mingw compiler, so the linking does not work.

**Comment by jyypma** [comment]
Did you compile NLopt from source?

**Comment by eddelbuettel** [comment]
@stefanoborini generally you should just let the package do its thing which, especially on Windows, is very standardized, tested and reliable.  As you can [see at CRAN](https://cloud.r-project.org/web/checks/check_results_nloptr.html) it builds on Windows (and for this post we can ignore the test error on Windows there for a second).

**Comment by stefanoborini** [comment]
@eddelbuettel I can't. I am running production here, and I have my own resolver for dependencies. CRAN only stores the compiled packages for the latest package. If they upgrade, they break our build.

**Comment by stefanoborini** [comment]
@jyypma no. I downloaded the NLopt 2.4 binary build as suggested by the readme.

**Comment by eddelbuettel** [comment]
@stefanoborini I don't follow. Even if you choose your own "resolver" and you use old versions, _those all built at CRAN at the time_.  What @jyypma and I are trying to convey is that it looks like you are overriding / switching compilers and breaking things in doing so.  The SO post you point at is useless (~ 11 years old) yet that type of linker error is seen when you, say, mix and match with different compilers, or otherwise forget to link with the C++ library (say call `gcc` when you needed to call `g++`).

Just trust the process and `R CMD INSTALL nlopt*` for whichever version you have.  For Windows, you _can_ also download an external version but you still _must_ plug it in where the [`src/Makevars.win`](https://github.com/jyypma/nloptr/blob/master/src/Makevars.win) expects them --- and use the exact same compiler R uses.   That has never been different in the 25 years I used R.  

Good luck.

**Comment by stefanoborini** [comment]
@eddelbuettel I am not. I literally downloaded NLopt version 2.4 compiled for windows as indicated here

https://github.com/jyypma/nloptr/blob/master/INSTALL.windows

Then I ran R CMD build on the downloaded nloptr 1.2.2.2 package. I am using R 3.6.3 and RTools35 (which is the one available for R 3.6.3). I have not changed anything. I am following the process strictly as documented and that's what I get. I have no idea why it works at CRAN.

**Comment by stefanoborini** [comment]
@eddelbuettel This is the actual screenshot of R CMD build execution

<img width="677" alt="Screenshot 2021-04-01 at 10 26 19" src="https://user-images.githubusercontent.com/132967/113273601-b9088f00-92d4-11eb-9c78-321f2739014d.png">

This is the version of RTools I am using

<img width="438" alt="Screenshot 2021-04-01 at 10 27 52" src="https://user-images.githubusercontent.com/132967/113274178-4c41c480-92d5-11eb-9f90-e75cd9e3f85f.png">

And this is the content of the nlopt.pc file I find in NLOpt 2.4, which I put on C:\tmp\nlopt

<img width="438" alt="Screenshot 2021-04-01 at 10 30 26" src="https://user-images.githubusercontent.com/132967/113274228-5bc10d80-92d5-11eb-9a85-58585a71c54a.png">

Windows is a windows 10 machine with nothing else installed. It's out of the box, plus R and Rtools. I am using cmd.exe, despite the powershell window, and I did set NLOPT_HOME to c:/tmp/nlopt

**Comment by jyypma** [comment]
Some people have had success with the binaries from
https://github.com/rwinlib/nlopt The directory structure is different than
the one used by the current nloptr Makevars.win file, so you would have to
re-arrange the files a bit.

The other option is to install NLopt from source as mentioned in the
INSTALL.windows file. This would allow you to make sure that the correct
compiler is used. If you happen to be successful, then a patch to the
description in INSTALL.windows would of course be much appreciated.

**Comment by eddelbuettel** [comment]
@stefanoborini You need figure out where your setup is different from CRAN.  They are are not all that generous with details but there is [this page](https://cloud.r-project.org/web/checks/check_flavors.html).  We are not privvy to any more information than you.

**Comment by stefanoborini** [comment]
@eddelbuettel my setup is a vanilla machine. The machines you are indicating are using GCC, not the RTools compiler, so you are intentionally breaking ABI compatibility with other packages and I am surprised it even works. RTools is the standard compiler used to compile R source packages. By compiling the package with GCC, the binary packages provided by CRAN have a completely different ABI compared to packages compiled in place for which there's no binary on cran or GCC available locally.

**Comment by stefanoborini** [comment]
@jyypma how did you compile the package provided at http://www.ucl.ac.uk/~uctpjyy/downloads/NLopt-2.4-win-build.zip ? Did you overwrite it with one compiled with the latest Rtools 4.0?

**Comment by jyypma** [comment]
The build you link to was created a few years ago. On windows I use Rtools
in combination with MSYS (to have access to Linux commands such as
configure). The script below I have used in the past to build a version of
NLopt using MSYS. It defines the compilers specified in Rtools when
configuring the NLopt build. Hope this helps.

===Contents of NLoptInstall.sh===
#!/bin/bash

R_HOME="C:/tools/R/R-3.3.1"
#R_ARCH="i386"
R_ARCH="x64"

NLOPT_SRC_DIR="C:/work/projects/R/nloptr/nlopt-2.4.2"
NLOPT_LIB_DIR="C:/work/projects/R/nloptr/nlopt-2.4.2-build"

PATH="C:\tools\R\Rtools\bin;C:\tools\R\Rtools\mingw_64\bin;${PATH}"

# Create directory for output
mkdir ${NLOPT_LIB_DIR}
mkdir ${NLOPT_LIB_DIR}/${R_ARCH}

# Start in source directory
cd ${NLOPT_SRC_DIR}

# Get R compilers and flags
CC=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CC`
CFLAGS=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CFLAGS`

CPP=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CPP`
CPPFLAGS=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CPPFLAGS`

#CXX=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CXX`
CXX="C:/tools/R/Rtools/mingw_64/bin/g++.exe"
CXXFLAGS=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CXXFLAGS`

CXXCPP=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config CXXCPP`

F77=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config F77`
FFLAGS=`"${R_HOME}/bin/${R_ARCH}/R.exe" CMD config FFLAGS`

echo "./configure --prefix=\"${NLOPT_LIB_DIR}/${R_ARCH}\" --disable-shared
--enable-static --without-octave --without-matlab --without-guile
--without-python --with-cxx CC=\"${CC}\" ADD_CFLAGS=\"${CFLAGS}\"
CPP=\"${CPP}\" ADD_CPPFLAGS=\"${CPPFLAGS}\" CXX=\"${CXX}\"
ADD_CXXFLAGS=\"${CXXFLAGS}\" CXXCPP=\"${CXXCPP}\" F77=\"${F77}\"
ADD_FFLAGS=\"${FFLAGS}\""

# Configure
./configure --prefix="${NLOPT_LIB_DIR}/${R_ARCH}" --disable-shared
--enable-static --without-octave --without-matlab --without-guile
--without-python --with-cxx CC="${CC}" ADD_CFLAGS="${CFLAGS}" CPP="${CPP}"
ADD_CPPFLAGS="${CPPFLAGS}" CXX="${CXX}" ADD_CXXFLAGS="${CXXFLAGS}"
CXXCPP="${CXXCPP}" F77="${F77}" ADD_FFLAGS="${FFLAGS}"

# Compile
make
make install

**Comment by astamm** [comment]
@stefanoborini can you install the latest 2.0.0 release to fit your needs?

**Comment by stefanoborini** [comment]
@astamm I don't know. I gave up on this.

**Comment by astamm** [comment]
Oh I see. No problem. Should I close the issue or do you intend to give it one more try?

**Comment by stefanoborini** [comment]
you can close it I guess. Thanks
