### ISSUE TITLE
initial values no longer changing

### ISSUE THREAD

**Issue by gray-logan** [astamm/nloptr#77]
Hi there,

I started using `nloptr` several months ago and was having no problems with it. For the last month or so, the "solution" the optimiser is returning is simply the initial values that I provide.

Some background: I'm trying to minimise a nonlinear function dependent on six input variables. The inputs are bounded between 0 and 1. Additionally, they are constrained to sum to 1.

**Things I've tried**:

-  using both the generalised `nloptr` function as well as the `slsqp` function
-  tinkering with the control parameters `ftol_rel`, `xtol_rel`, `ftol_abs`, `xtol_abs`, and `maxeval` to no avail.
-  using different values for my initial conditions
-  running without my bounds or my constraints
-  switching between defining constraints as "equality" or "inequality" constraints (i.e. putting them in as `hin` vs `heq`) 
-  updated `nloptr` to v 1.2.2.2 (my code was working before on the version before this)
-  rolling back the version to what my code used to work with
-  updating R to 4.x

Here's my setup for calling the function: 

```
constraints <- function(x, pars, initial.conditions) { return(sum(x) - 1) }

solution <- slsqp(
  x0 = rep(1/6, 6),
  fn = growth_model,
  lower = rep(0, 6),
  upper = rep(1, 6),
  hin = constraints,
  pars = pars, # passed from the objective function
  initial.conditions = initial_y # passed from the objective function
)

```

I've included the objective function code (and other code that it needs to run) as an attachment to avoid clutter just in case it is necessary. 
[extra-files.zip](https://github.com/jyypma/nloptr/files/6812220/extra-files.zip)

Please let me know if I have left out any important information; I'm a github noob and this is the first time I've asked a question, so please let me know if I've forgotten something obvious.

Thanks a bunch,

Logan

**Comment by jyypma** [comment]
It looks like your objective function does not depend on `x`. E.g. the following code approximates the gradient of the objective function in the starting point of the optimization:
`nloptr:::finite.diff(func = growth_model, .x = rep(1/6, 6), pars = pars, initial.conditions = initial_y)`
with the following result
`[1] 0 0 0 0 0 0`
Since the objective function is flat at the initial value for `x` and the constraints are met, the optimizer exits with the message that the procedure converged.

Does this help?

**Comment by gray-logan** [comment]
This does help, thank you. I'll make some changes and then see if things work.

Thanks again for the info and the quick reply.

Logan

**Comment by gray-logan** [comment]
This worked!

Thanks again,

Logan
