### ISSUE TITLE
Lagrangian multiplier from auglag 

### ISSUE THREAD

**Issue by waiyujack** [astamm/nloptr#78]
Hi I have been exploring the package recently and I wonder if there is a way I can extract the Lagrangian multiplier term from the `auglag()` output?

**Comment by astamm** [comment]
Hey. Thanks for reaching out. It is currently not possible to extract them. If there is a way to extract them in the original NLOpt library, I could think about giving access to them as well in **nloptr**. Do you know if such a thing is doable with the C library?

**Comment by BertvanderVeen** [comment]
I wonder if this discussion could be of use for this issue: https://github.com/stevengj/nlopt/issues/327, see also https://github.com/stevengj/nlopt/issues/405.

**Comment by aadler** [comment]
As mentioned above, this is something which would have to be exposed in NLOPT before anything can be done in nloptr, so this probably a **wontfix** since we cannot fix it.

**Comment by astamm** [comment]
Following @aadler's advice, I will close the issue. Should nlopt expose the feature, you could reopen an issue.
