### ISSUE TITLE
Argument parsing in nloptr(, ...)

### ISSUE THREAD

**Issue by tseaward** [astamm/nloptr#8]
Line 69 of nloptr has stop(...) if arguments passed to a function are not required by that function. Should it not rather use warnings()?

For example eval_f might require an additional argument named a, while eval_g_ineq might require an additional argument named b, but not a.

**Comment by tseaward** [comment]
In the interim I have used the following (not the best solution but workable)

```
...
arg <- c(formals(fn), formals(hin), formals(heq), list(...))
arg <- arg[unique(names(arg))]

formals(fn) <- arg
formals(heq) <- arg
formals(hin) <- arg

res <- nloptr(x0, fn, NULL, etc etc)
...
```

**Comment by jyypma** [comment]
Hi Terry,

thank you for your message. What  problems do you run into when adding both
a and b as arguments to both objective and constraint functions? The
arguments do not have to be used inside the functions, but supplying them
makes it very explicit that both functions use the same data.

Best wishes,
Jelmer

**Comment by tseaward** [comment]
Hi Jelmer,

That works, but in my case the user should only pass arguments that the
function requires and nloptr (my version at least) takes care of the rest.
It's not intuitive to provide arguments the function does not use so I feel
it's best to hide that from the user by using the code below. Again I must
stress this is in my situation and (possibly) not generally.
