### ISSUE TITLE
CRAN 1.2.2.3 Windows Binaries

### ISSUE THREAD

**Issue by slodge** [astamm/nloptr#80]
Looking at the current binary status on CRAN it seems 1.2.2.2 is current while 1.2.2.3 is old 

From https://cran.r-project.org/web/packages/nloptr/index.html - `**r-release: nloptr_1.2.2.2.zip, r-oldrel: nloptr_1.2.2.3.zip**`

<html>
<body>
<h4 style="background: white; color: rgb(102, 102, 102); font-family: monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Downloads:</h4>

Package source: | nloptr_1.2.2.3.tar.gz
-- | --
Windows binaries: | r-devel: nloptr_1.2.2.3.zip, r-devel-UCRT: nloptr_1.2.2.3.zip, r-release: nloptr_1.2.2.2.zip, r-oldrel: nloptr_1.2.2.3.zip
macOS binaries: | r-release (arm64): nloptr_1.2.2.2.tgz, r-release (x86_64): nloptr_1.2.2.3.tgz, r-oldrel: nloptr_1.2.2.3.tgz
Old sources: | nloptr archive

<br class="Apple-interchange-newline">
</body>
</html>

Is it possible to give CRAN a nudge on this?

Apologies if this is a duplicate - I couldn't see it here already (but I've missed things before!)

**Comment by eddelbuettel** [comment]
You need to ask CRAN this. We as maintainers have _zero_ control over this.

**Comment by slodge** [comment]
Understood. Email sent to CRAN.

**Comment by astamm** [comment]
We just released `v2.0.0`. Binaries for windows and macOS are on their way.
