### ISSUE TITLE
source(test-all.R) failed on centos8_x86_64

### ISSUE THREAD

**Issue by Tom-python0121** [astamm/nloptr#81]
hello,I meet a problem:source(test-all.R) failed on centos8_x86_64

### Steps to reproduce the issue

```console
[root@localhost tests]#Rscript test-all.R
Loading required package: nloptr
[1] 1.000000 4.743006 3.821141 1.379409
[1] 1.000000 4.743000 3.821150 1.379408
== Failed tests =============================================================================================================================================================================================
-- Failure (test-hs071.R:98:5): Test HS071. ------------------------------------
res$solution not equal to `solution.opt`.
3/4 mismatches (average diff: 5.54e-06)
[2] 4.74 - 4.74 ==  6.69e-06
[3] 3.82 - 3.82 == -8.73e-06
[4] 1.38 - 1.38 ==  1.21e-06

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 46 ]
Error: Test failures
Execution halted
[root@localhost tests]#R
> source("test-all.R")
Loading required package: nloptr
[1] 1.000000 4.743006 3.821141 1.379409
[1] 1.000000 4.743000 3.821150 1.379408
Called from: eval(code, test_env)
Browse[1]> debug(expect_equal)
Browse[1]> expect_equal(res$solution, solution.opt, tolerance = 1e-6)
debugging in: expect_equal(res$solution, solution.opt, tolerance = 1e-06)
debug: {
    act <- quasi_label(enquo(object), label, arg = "object")
    exp <- quasi_label(enquo(expected), expected.label, arg = "expected")
    if (edition_get() >= 3) {
        expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
    }
    else {
        if (!is.null(tolerance)) {
            comp <- compare(act$val, exp$val, ..., tolerance = tolerance)
        }
        else {
            comp <- compare(act$val, exp$val, ...)
        }
        expect(comp$equal, sprintf("%s not equal to %s.\n%s",
            act$lab, exp$lab, comp$message), info = info)
        invisible(act$val)
    }
}
Browse[4]> c
Error: res$solution not equal to `solution.opt`.
3/4 mismatches (average diff: 5.54e-06)
[2] 4.74 - 4.74 ==  6.69e-06
[3] 3.82 - 3.82 == -8.73e-06
[4] 1.38 - 1.38 ==  1.21e-06
```
Can you tell me why this problem happened?

**Comment by jyypma** [comment]
This test checks whether the correct optimum is found for an optimization
problem where the solution is known (example problem number 71 from the
Hock-Schittkowsky test suite). The test fails because the solution found by
nloptr differs more from the known solution than specified by the tolerance
in the test. The tolerance in the test is probably a bit too strict in this
case (1e-6), see line 97 of
https://github.com/cran/nloptr/blob/master/tests/testthat/test-hs071.R. The
test will pass if the tolerance in the test is set to 1e-5. Does this
answer your question?

**Comment by Tom-python0121** [comment]
@jyypma how is tolerance calculated?I want to know.My problem has been fixed according to your method. The patch is as follows:
diff --git a/tests/testthat/test-hs071.R b/tests/testthat/test-hs071.R
index 3cb3fb8..d1cea50 100644
--- a/tests/testthat/test-hs071.R
+++ b/tests/testthat/test-hs071.R
@@ -94,7 +94,7 @@ test_that( "Test HS071.", {
                    opts        = opts )

     # Run some checks on the optimal solution.
-    expect_equal(res$solution, solution.opt, tolerance = 1e-6)
+    expect_equal(res$solution, solution.opt, tolerance = 1e-5)
     expect_true(all(res$solution >= lb))
     expect_true(all(res$solution <= ub))
the result:
![image](https://user-images.githubusercontent.com/77763324/142963322-b3fe3486-712d-4175-ad62-1401230f96cc.png)
Can this patch be incorporated into the latest version?
