### ISSUE TITLE
Optional package used unconditionally

### ISSUE THREAD

**Issue by eddelbuettel** [astamm/nloptr#89]
You probably want to add a `skip_if_not_installed("xml2")` (or whatever `testthat` calls it) here.   Assuming a package in Suggests: is always present is an error, and the _Writing R Extensions_ manual is getting clearer and clearer on it.  CRAN still tolerates it, it shouldn't.

![image](https://user-images.githubusercontent.com/673121/149374178-5ed0f5fd-fb6c-41ef-ad1d-c5be0484cf34.png)

**Comment by astamm** [comment]
Oops, you are absolutely right. I will fix that.

**Comment by astamm** [comment]
Should be fixed by 6e9ec94.
