### ISSUE TITLE
configuration fails if 'ed' is not available on the system

### ISSUE THREAD

**Issue by JensTimmerman** [astamm/nloptr#9]
do you really need 'ed' to do the configuration step?
The configure script should check for the presence of 'ed' before trying to use it, and provide a clean error message (or an alternative way of 'patching' a file)

**Comment by sfromm-plm** [comment]
I agree.  I was building this package via Chef and noticed some warnings.

My impression:  `ed` wasn't installed by default on the base Centos 7.2 configuration.  When the `configure` script ran, three lines with `ed` failed, but only issued warnings, and did not cause `configure` to fail.

I didn't run a test to see whether this materially affected the build.

**Comment by jyypma** [comment]
`ed` is no longer used during configure, see commit 9871dfdc1ad1c027135eb367b3c798129f36679b.

**Comment by sfromm-plm** [comment]
Thank you!
