### ISSUE TITLE
Test hardwires version

### ISSUE THREAD

**Issue by eddelbuettel** [astamm/nloptr#90]
Here we have

```r
> Sys.setenv(PKG_LIBS="-lnlopt")
> Rcpp::cppFunction("std::vector<int> ver() { int ma, mi, bu; nlopt_version(&ma, &mi, &bu); std::vector<int> v = {ma, mi, bu}; return v; }", depends="nloptr", include="#include <nlopt.h>")
> ver()
[1] 2 7 1
> 
```

yet the test hard wires 2, 7, and 0 which is bound to fail.

**Comment by astamm** [comment]
I believe your last commit on the PR #88 that I just merged fixes this issue, is that correct?

**Comment by eddelbuettel** [comment]
Yup. Had to to pass the tests (as I provided 2.7.1).  Issue mostly filed to not forget about it and to give you a chance to think about what you want here.  The `>=` may be the best answer -- the minimum version tests is typically done at build time anyway.

**Comment by astamm** [comment]
I added the `>=` to major and minor version number as well to pass the unit test for any version >= 2.7.0 in 6e9ec94.
