### ISSUE TITLE
deprecate jyypma repo/make this primary

### ISSUE THREAD

**Issue by bbolker** [astamm/nloptr#91]
This is low priority, but it would be a good idea - once the dust has settled on the current CRAN release - to do something to reduce confusion/clarify that this is now the up-to-date version of the package repo. (IMO doesn't really matter whether that's done by merging this fork back into @jyypma's repo, or that repo gets a prominent notice in its README file directing people here, or ...)

**Comment by eddelbuettel** [comment]
I think it already is as I have the old one as parentrepo

```sh
edd@rob:~/git/nloptr(feature/build_options)$ git remote -v
origin  git@github.com:eddelbuettel/nloptr.git (fetch)
origin  git@github.com:eddelbuettel/nloptr.git (push)
parentrepo      https://github.com/jyypma/nloptr.git (fetch)
parentrepo      https://github.com/jyypma/nloptr.git (push)
edd@rob:~/git/nloptr(feature/build_options)$ 
```

yet my commit end up here.  So methinks what you ask for already happend. 

You can check that too by adding the (correct, if I may, with two `y` not one as above) URL into a webbrowser:  https:// github dot com slash jyypma slash nloptr will get you here.   So feel free to close this (unless I am halluzinating and missed something here)

**Comment by bbolker** [comment]
Huh, you're right (not that that's surprising).  Either I'm dreaming or this has changed fairly recently - when the CRAN brouhaha started it took me a while to get unconfused/find my way to this repo.

**Comment by eddelbuettel** [comment]
Yes, it was in the last few days, it also caught me by (very friendly) surprise as I like you had made myself a mental note to follow up on this.   The way that moved or renamed repos get auto-forwarding links is one of the nicer (if quiet) GitHub features.
